#!/usr/local/bin/bash
echo "Reading bingo numbers..."
IFS="," read -r -a bingonumbers <<< "$(head -1 input)"

echo "Reading boards..."
declare -i board=1
declare -A boards
declare -i x=0
declare -i y=0
declare -a row
while read line; do
  if [ "$line" == "" ]; then
    (( board++ ))
    (( y=0 ))
    continue
  fi
  read -r -a row <<< "$line"
  for x in `seq 0 4`; do
    boards["$board,$y,$x"]=${row[$x]}
  done
  (( y++ ))
done <<< "$(tail +3 input)"

print_boards () {
  for b in `seq 1 $board`; do
    for y in `seq 0 4`; do
      for x in `seq 0 4`; do
        printf "%2d " ${boards["$b,$y,$x"]}
      done
      echo
    done
    echo
  done
}

mark_bingo_number () {
  drawnnumber=$1
  for b in `seq 1 $board`; do
    for y in `seq 0 4`; do
      for x in `seq 0 4`; do
        if [ ${boards["$b,$y,$x"]} -eq $drawnnumber ]; then
          (( boards["$b,$y,$x"]=-1 ))
        fi
      done
    done
  done
}

check_for_bingo () {
  for b in $@; do
    for y in `seq 0 4`; do
      declare -i sum=0
      for x in `seq 0 4`; do 
        (( sum=sum+${boards["$b,$y,$x"]} ))
      done
      if [ $sum -eq -5 ]; then
        echo $b
        return
      fi
    done
    for x in `seq 0 4`; do
      declare -i sum=0
      for y in `seq 0 4`; do
        (( sum=sum+${boards["$b,$y,$x"]} ))
      done
      if [ $sum -eq -5 ]; then
        echo $b
        return
      fi
    done
  done
  echo 0
}

declare -a non_bingo_boards=($(seq 1 $board))

echo "Playing..."
for i in ${bingonumbers[@]}; do
  # Check for bingo
  while : ;do
    bingo="$(check_for_bingo "${non_bingo_boards[@]}")"
    if [ $bingo -gt 0 ]; then
      echo "Bingo on board ${bingo[@]}"
      lastbingo=$bingo
      declare -A lastboard=()
      for y in `seq 0 4`; do
        for x in `seq 0 4`; do
          printf "%2d " ${boards["$lastbingo,$y,$x"]}
          lastboard["$y,$x"]=${boards["$lastbingo,$y,$x"]}
        done
        echo
      done
      unset non_bingo_boards[$((bingo - 1))]
      echo ${non_bingo_boards[@]}
    else
      break
    fi
  done
  if [ ${#non_bingo_boards[@]} -eq 0 ]; then
    echo "No boards left!"
    break
  fi
  mark_bingo_number $i
  lastdraw=$i
done

declare -i sum=0
for y in `seq 0 4`; do
  for x in `seq 0 4`; do
    printf "%2d " ${lastboard["$y,$x"]}
    if [ ${lastboard["$y,$x"]} -ge 0 ]; then
      (( sum=sum+${lastboard["$y,$x"]} ))
    fi
  done
  echo
done
echo $(( $sum * $lastdraw))
